[package]
authors = ["Josh Leverette <coder543@gmail.com>"]
name = "xray"
version = "0.1.0"

[dependencies]
byteorder = "1.2.1"
flate2 = "1.0.1"
nom = "5.0.0"
rayon = "1.1.0"
rayon-hash = "0.5.0"
rustyline = "5.0.0"
structopt = "0.2.18"
whatlang = "0.7.1"
