[package]
name = "xray"
version = "0.1.0"
authors = ["Josh Leverette <coder543@gmail.com>"]

[dependencies]
whatlang = "0.5.0"
structopt = "0.1.6"
structopt-derive = "0.1.6"
rayon = "0.9.0"
rustyline = "1.0.0"

[dependencies.nom]
version = "3.2.1"